# LPIPS + Eosin channel
_target_: preprocessors.paired_preprocessors.PairedCellPreprocessingPipeline
preprocessors:
  - _target_: preprocessors.cell_preprocessors.ToRGB
  - _target_: preprocessors.cell_preprocessors.MinMaxNormalizer
  - _target_: preprocessors.cell_preprocessors.HEDChannelExtractor
    mode: eosin
  - _target_: preprocessors.cell_preprocessors.MinMaxNormalizer
  - _target_: preprocessors.cell_preprocessors.ToRGB
  - _target_: preprocessors.cell_preprocessors.ScaleToMinusOneOne
  - _target_: preprocessors.cell_preprocessors.ToTensor
