# Fedor config 1: squeeze_avg_rgb
# normalization=True, rgb, flip=True, histmatch=True, clahe=True
_target_: preprocessors.paired_preprocessors.PairedCellPreprocessingPipeline
preprocessors:
  - _target_: preprocessors.cell_preprocessors.ToRGB
  - _target_: preprocessors.cell_preprocessors.ToUint8
  - _target_: preprocessors.cell_preprocessors.ClahePreprocessor
    clip_limit: 2.0
    tile_grid_size: [8, 8]
  - _target_: preprocessors.cell_preprocessors.MinMaxNormalizer
  - _target_: preprocessors.cell_preprocessors.FlipIntensity
  - _target_: preprocessors.paired_preprocessors.MatchHistograms
    match_to: src
  - _target_: preprocessors.cell_preprocessors.ScaleToMinusOneOne
  - _target_: preprocessors.cell_preprocessors.ToTensor
