# Config 2: alex_avg_rgb
# Expected: normalization=False, rgb, flip=False, histmatch=True, clahe=False
# normalization=False => ToFloat (просто /255) вместо MinMaxNormalizer (channel-wise)
_target_: preprocessors.paired_preprocessors.PairedCellPreprocessingPipeline
preprocessors:
  - _target_: preprocessors.cell_preprocessors.ToRGB
  - _target_: preprocessors.cell_preprocessors.ToFloat
  # flip=False, clahe=False
  - _target_: preprocessors.paired_preprocessors.MatchHistograms
    match_to: src
  - _target_: preprocessors.cell_preprocessors.ScaleToMinusOneOne
  - _target_: preprocessors.cell_preprocessors.ToTensor
