defaults:
  - dataset: paired_image_dist
  - preprocessor: paired_cell_pipeline
  - metric: cellpose
  - evaluator: quality_corrs
  - _self_

# Имя эксперимента
name: cellpose_baseline

seed: 42

hydra:
  run:
    dir: outputs/${name}_${now:%Y%m%d_%H%M%S}
  sweep:
    dir: outputs/multirun
    subdir: ${name}_${now:%Y%m%d_%H%M%S}
