# LPIPS AlexNet with average aggregation (not learned linear)
_target_: metrics.similarity_estimators.LPIPSSimilarityEstimator
lpips_args:
  net: alex
  lpips: false  # avg aggregation
  spatial: false
  version: "0.1"
device: cuda
